### ISSUE TITLE
rpi-gpio node does not work

### ISSUE THREAD

**Issue by vicfergar** [hassio-addons/addon-node-red#54] opened 2018-10-17 21:46 UTC
# Problem/Motivation
rpi gpio nodes does not work with:
Hardware: RPi3 Model B 
Software:
- HassOS 1.11
- Hass.io supervisor 138
- Home Assistant 0.80.2
- Node-RED add-on 0.7.0

## Expected behavior

GPIO shold work with Node-RED rpi gpio node and GPIO should change voltage.

## Actual behavior

Node doesn't work because GPIO does not change voltage. 
The log shows this warning:
![image](https://user-images.githubusercontent.com/6979979/47117996-428f8800-d266-11e8-97bc-5df626189f44.png)

## Steps to reproduce

Use the hardware and software defined and add a rpi gpio in Node-RED add-on. Changing the node state does not affect the physical pin voltage.

## Proposed changes

None

**Comment by aluminium1** [comment] 2018-11-02 11:16
Got the same error, gpios via home-assistant directly work, but only in node-red it doesnt work.

HassOS 32-bit 1.12
Supervisor v. 138
Node-RED add-on 1.0.1

**Comment by cyberThomasRocks** [comment] 2018-12-16 05:55
Any update on this? Will an older version work?

**Comment by frenck** [comment] 2018-12-16 07:49
No update on this and no an older version won't work.

**Comment by mu3** [comment] 2019-02-16 07:07
People on the forum are [saying](https://community.home-assistant.io/t/rpi-gpio-raspberry-pi-3-b-hassos-1-5/59537/4) it's working on 32x.
@frenck Could you please clarify what's the of the issue and should users expect a fix in the foreseeable future?

**Comment by frenck** [comment] 2019-02-16 11:58
@mu3 No I can't.
Feel free to contribute a fix.

**Comment by pobl** [comment] 2019-02-21 11:19
@frenck 
Hassio can see the RPi GPIO pin status through configuration.yaml and the Home Assistant can see /dev/gpiomem. It is not therefore a hassio problem as such. It would seem though, that the nodered container - cannot see /dev/gpiomem, I am no container expert (had to use portainer to diagnose this) but could this be why this is not working? 

Rgds

John W

**Comment by pobl** [comment] 2019-02-21 15:22
OK so a bit more tinkering and research and I found that running the nodered container in privilege mode and adding /dev/gpiomem device as resource to container fixed it. Steps to achieve this - before starting - importantly make sure you have a backup!!! 

1) Install Portainer
2) Take HASSIO snapshots and backups
3) Login and locate Nodered container in portainer, click the link (in my case it was: addon_a0d7b954_nodered)
![image](https://user-images.githubusercontent.com/31574186/53179193-27090500-35eb-11e9-9d84-f955511e6bc0.png)

4) Click Duplicate/Edit
![image](https://user-images.githubusercontent.com/31574186/53179248-46a02d80-35eb-11e9-8e51-5eff9652dd0c.png)

5) Scroll to bottom section of page on the Right hand side click Runtime and resources
![image](https://user-images.githubusercontent.com/31574186/53179422-8f57e680-35eb-11e9-900f-1561d4caf102.png)

6) Enable privilege mode and add /dev/gpiomem as a resource available to the container
![image](https://user-images.githubusercontent.com/31574186/53179657-0f7e4c00-35ec-11e9-9a5a-d54d797c607d.png)

7) Click deploy the container
![image](https://user-images.githubusercontent.com/31574186/53179690-1e64fe80-35ec-11e9-9f7d-0b483fffc9b7.png)

Mileage may vary but with some luck this helps y'all.

Rgds
John W

**Comment by frenck** [comment] 2019-02-21 15:56
@pobl I've deleted your comment. That method **WILL BREAK** things and I don't want anyone to every try it.

**Comment by pobl** [comment] 2019-02-21 16:01
> @pobl I've deleted your comment. That method **WILL BREAK** things and I don't want anyone to ever try it or feel like it is a solution.

So could you elaborate on why please?

**Comment by frenck** [comment] 2019-02-21 18:53
@pobl Using a privileged container is generally considered bad and something Hass.io will not allow/is not capable of for that same reason. 

Overriding that manually will cause issues since the supervisor manages the container, which you just broke (good luck installing the next update without issues).

**Privileged mode is NEVER a solution**, it is just a lack of doing it the right way.

**Comment by pobl** [comment] 2019-02-21 19:23
@Frenck with respect, we do not know each other. However, one thing is clear I'm not the developer/maintainer, you are. I like many of the other people following this post (and others) are facing the same challenge, I just came up with a potential workaround which I am fairly sure **some** of the followers would be willing to implement if it means they can fix their problems (albeit temporarily). Whilst you as the developer/maintainer crack on with fixing the root cause of the issue and making it available in the next release. 

I do appreciate that Hassio for a lot of people is a labour of love and I am only trying to help out with some observations and interesting pointers - if its not helping you then just say so. The open source community and everyones efforts with Hassio is truly amazing. Clearly though, something is wrong with this Nodered set up with RPi GPIO and it does need some of your valuable attention. 

Rather than just dismissing people with off hand comments like _if you think stuff is wrong please file an issue_ or _please contribute a fix_, perhaps a more appreciative response to the community wouldn't go a miss, just once in a while. I for one spent a fair bit of time ascertaining the facts that I did. If privilege mode makes it work (rightly or wrongly) surely that helps you understand more about the problem?

It saddens me to conclude that you don't seem to value that.

Rgds

JW

**Comment by frenck** [comment] 2019-02-21 19:33
> you as the developer/maintainer crack on with fixing the root cause of the issue and making it available in the next release.

Seems like you concluded it already, and according to your conclusions, it is an external upstream issue, which is out of my control then, isn't it?

> if its not helping you then just say so

I did tell you that since I told you I did remove your post.

> Clearly though, something is wrong with this Nodered set up with RPi GPIO

The use-case and userbase for this feature are rather small, unfortunately for a lot of you. Secondly, Hass.io does not only do Raspberry Pi, while your conclusions seem fairly simple, but we also have to deal with tons of other device types that handle stuff differently.

> appreciative response to the community wouldn't go a miss, just once in a while

I'm sorry, thank you for your help. I like to be direct, to the point and straight forward. For you, I will make an exception in the future and add some unneeded fluff in the future. As my GitHub profile (and any other profile) states: I'm slightly assholic.

> If privilege mode makes it work (rightly or wrongly) surely that helps you understand more about the problem

What made you think I didn't understand the problem?
Maybe just install it straight onto the host system... that will work as well!

Thanks for your help, and insights.

Let us continue with working on the dozen of issues, problems, feature requests, add-on requests, and other stuff, I do out my free will and spare time.

../Frenck

**Comment by pobl** [comment] 2019-02-21 20:01
Assholic - not a word but thanks for clarifying. Jeez!

**Comment by pobl** [comment] 2019-02-22 13:12
To answer your other question....
This is what led me to think you didn't understand the problem.
![image](https://user-images.githubusercontent.com/31574186/53244691-89254100-36a3-11e9-9183-08bb5689a2ee.png)

**Comment by mu3** [comment] 2019-02-22 20:25
@frenck please stop removing @pobl’s comments. This is not a respectful behavior.
You have many other issues to fix with a higher priority — it is easily understandable.
Nobody comes here to fight but together solve the problems. Shutting someone’s mouth is not a solution and it just doesn’t smell good.
✌️

**Comment by frenck** [comment] 2019-02-26 08:43
@mu3 Sorry to hear you don't agree, and that is fine by me. @pobl had been banned from this for a period of 30 days. I'm happy to discuss solutions, a workaround, and fixes without any pointing fingers or placing demands.

Please let us stay on topic here. If you want to discuss this future, I suggest you'd hop on Discord. This floated in all kinds of directions already.

**Comment by Misiu** [comment] 2019-04-16 12:33
@frenck there is an unofficial 64-bit GPIO library: https://github.com/TheNextLVL/RPi.GPIO.64 will it help to solve the issue?
If not maybe we could ask in upstream repo for a fix?
I want to setup new instance and GPIO support is one of requirements, so a permanent fix would be awesome :)

**Comment by acmkonings** [comment] 2019-04-19 21:23
Don't know if it is of any help, but I tried the commandline gpio tool and I get the following error: 

`/sys/class/gpio/export: Read-only file system`

Being root on the system, this surprised me. But then again, the Raspberry Pi still has a lot of secrets for me. Anyway, could this be the source of trouble?

**Comment by truglodite** [comment] 2019-06-17 16:34
I had the same problem when I tried to use the RPi GPIO nodes in nodered for digital outputs, but was able to workaround it in a way I think is more true to the game of keeping devices on hassio and logic on nodered (most common method). Simply use the hassio built in rpi_gpio platform to create nodes for the GPIO pins:

e.g.
```
switch:
  - platform: rpi_gpio
    ports:
      12: Beeper
      16: Siren1
      13: Siren2
```
Then use those nodes like any other service call in nodered (eg switch.Beeper, etc). That said, I am new to hassio/nodered and don't know if the hassio gpio stuff handles PWM like the nodered gpio is supposed to.

**Comment by frenck** [comment] 2019-07-21 11:41
RPi.GPIO for aarch64 is now in beta, awaiting final release to get this bug out of the way (finally!)

**Comment by frenck** [comment] 2019-07-21 13:57
Are they looking at this topic? Just minutes ago it has been released. Going to upgrade this asap.

**Comment by frenck** [comment] 2019-07-22 06:24
New version has been released. Looking for testers/confirmation

**Comment by frenck** [comment] 2019-07-26 17:44
Closing issue.

**Closed by frenck** 2019-07-26 17:44 UTC
Labels: Status: Triage, Type: Bug
