### ISSUE TITLE
500 Error accessing Web Server

### ISSUE THREAD

**Issue by dennisracine** [hassio-addons/addon-node-red#864] opened 2021-01-24 11:27 UTC
# Problem/Motivation
"500 Internal Server Error" when going to web interface. (Accessing via the HA panel sidebar does work within HA, but does not when going directly with a web browser ie https://my.duckdns.org:1880

Version 8.0.0

Logs:

2021/01/24 03:11:20 [error] 577#577: *309 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.68.66, server: a0d7b954-nodered, request: "GET / HTTP/2.0", host: "my.duckdns.org:1880"
[24/Jan/2021:03:11:20 -0800] 500 -(192.168.68.66) GET / HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36)
2021/01/24 03:11:20 [error] 577#577: *309 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.68.66, server: a0d7b954-nodered, request: "GET /favicon.ico HTTP/2.0", host: "my.duckdns.org:1880", referrer: "https://my.duckdns.org:1880/"

**Comment by frenck** [comment] 2021-01-24 11:42
duplicate of #824

**Closed by frenck** 2021-01-24 11:42 UTC
