### ISSUE TITLE
Node-RED failed start after update to version: 7.2.9

### ISSUE THREAD

**Issue by vlad36N** [hassio-addons/addon-node-red#765] opened 2020-11-18 11:29 UTC
# Problem/Motivation

Updated to version: 7.2.9

## Expected behavior

Has been working version: 7.2.8

## Actual behavior
Node-RED failed start. Log: 
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 FAILED at 531.
1 out of 1 hunk FAILED -- saving rejects to file nodes/ui_base.html.rej
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
## Steps to reproduce

Update

**Comment by abneits** [comment] 2020-11-18 11:32
Same problem

**Comment by frenck** [comment] 2020-11-18 11:33
Duplicate of #764

Please check existing issues before opening a new one. Gets you the answer faster, saves me the effort of handling duplicates.

Thanks 👍

**Closed by frenck** 2020-11-18 11:33 UTC
