### ISSUE TITLE
HTTP Error 500 when connecting on port 1880

### ISSUE THREAD

**Issue by Malaga82** [hassio-addons/addon-node-red#862] opened 2021-01-23 22:31 UTC
# Problem/Motivation

Connection on port 1880 goes into: 500 Internal Server Error by nginx
Home Assistant Supervised

## Expected behavior

Prompt for use/password and login into nodered webUI

## Actual behavior

Only a blank page with the message: 500 Internal Server Error nginx

## Steps to reproduce

Update to version 8.0.0, fill http_node and http_static with user/password, fill 1880 port on Host and try to login.

## Proposed changes

Here is the log:

```
`2021/01/23 23:06:11 [error] 570#570: *1 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.x.y, server: a0d7b954-nodered, request: "GET / HTTP/1.1", host: "192.168.x.x:1880"
[23/Jan/2021:23:06:11 +0100] 500 -(192.168.x.y) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36)
2021/01/23 23:06:12 [error] 570#570: *2 lua entry thread aborted: runtime error: /usr/share/lua/common/resty/core/request.lua:124: no request found
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/share/lua/common/resty/core/request.lua:124: in function 'get_headers'
	/etc/nginx/lua/ha-auth.lua:7: in function 'authenticate'
	/etc/nginx/lua/ha-auth.lua:73: in function </etc/nginx/lua/ha-auth.lua:1>, client: 192.168.x.y, server: a0d7b954-nodered, request: "GET /favicon.ico HTTP/1.1", host: "192.168.x.x:1880", referrer: "http://192.168.x.x:1880/"`
```

**Comment by sinclairpaul** [comment] 2021-01-23 22:46
Duplicate of #824 ?, please confirm the architecture/hardware you are running

**Comment by Malaga82** [comment] 2021-01-23 22:53
I didn't check the other posts, my bad, but it's the same as https://github.com/hassio-addons/addon-node-red/issues/824#issuecomment-765673806
I'm on core-0.115.6
supervisor-2021.01.5

**Comment by sinclairpaul** [comment] 2021-01-23 23:05
Will close it out as its a duplicate, you can thumbs up the other issue.

**Closed by sinclairpaul** 2021-01-23 23:05 UTC
