### ISSUE TITLE
NO NODE STATUS

### ISSUE THREAD

**Issue by goldbe4804** [hassio-addons/addon-node-red#1636] opened 2023-07-11 17:29 UTC
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2023-07-11 17:31
Hi 👋 

Seems like your capslock was stuck while writing the subject of this issue (please note, that is considered shouting in general, which wasn't really needed?)

Also, the issue is empty, nothing was written down. Therefore, closing this issue.

../Frenck

**Closed by frenck** 2023-07-11 17:31 UTC

**Comment by goldbe4804** [comment] 2023-07-11 17:40
haven't used node red in a bit- went to update something and saw that the nodes have nothing under them - i dont know how long its been like this- i did try to restore node red also reinstalled it with the same outcome -- the automations do seem to be working- dont know what to try next---- somtimes if i stop and restart NR it will be ok till i go to another page the come [back](![nr](https://github.com/hassio-addons/addon-node-red/assets/56876314/dcba496e-5aa3-476d-8bdb-1f438939411a))
node red 3.0.2
ha 2003.7.1
thanks
