### ISSUE TITLE
Bad gateway after updating to 7.2.9

### ISSUE THREAD

**Issue by kersten-lohmeyer** [hassio-addons/addon-node-red#767] opened 2020-11-18 12:27 UTC
Home Assistant 0.117.6
Hass.os 4.16

After Updating from Node-RED 7.2.8 to 7.2.9 I get a "bad gateway" message. I already tried restarting the Pi 4 to no extent.

Error message in logs was something like "Watchdog found a problem with Node-RED addon". (I already restored a snapshot, thats's why I can't tell exactly).

**Comment by frenck** [comment] 2020-11-18 12:49
Duplicate of #764, #765 and #766.

Please check existing issues before opening a new one. Gets you the answer faster, saves me the effort of handling duplicates.

Thanks 👍

**Closed by frenck** 2020-11-18 12:49 UTC

**Comment by kersten-lohmeyer** [comment] 2020-11-18 12:51
I didn't see an open Issue because they were all already closed.

**Comment by frenck** [comment] 2020-11-18 12:58
Yes, that was the point. It has already been resolved and closed.
