### ISSUE TITLE
Node Red UI Not Loading on 2022.8

### ISSUE THREAD

**Issue by Scags104** [hassio-addons/addon-node-red#1411] opened 2022-08-03 18:59 UTC
# Problem/Motivation

Node Red shows as "Not Started" and the UI wont load. When looking at the logs it seems it is started and running as usual. On the Addons page it also shows as not started and pressing start does nothing.

## Expected behavior

Expected Behavior: Node Red UI should load instead of being prompted to start the addon

## Actual behavior

Actual Behavior: Being promted to start the addon

## Steps to reproduce

Try to get to the Node Red UI

## Proposed changes

Assumption: Supervisor issue

# Logs

subsection of recurring log entries in the NodeRed addon:
`3 Aug 12:16:39 - [info] [server:Home Assistant] Connecting to http://supervisor/core`
`3 Aug 12:16:44 - [info] [server:Home Assistant] Connecting to http://supervisor/core`
`3 Aug 12:16:49 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:16:54 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:16:59 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:17:04 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:17:09 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:17:14 - [info] [server:Home Assistant] Connecting to http://supervisor/core` 
`3 Aug 12:17:19 - [info] [server:Home Assistant] Connecting to http://supervisor/core`

**Comment by frenck** [comment] 2022-08-03 21:10
duplicate of #1410

**Closed by frenck** 2022-08-03 21:10 UTC
