### ISSUE TITLE
Connection to home assistant shows disconnected since 2023.1.2

### ISSUE THREAD

**Issue by magiva** [hassio-addons/addon-node-red#1543] opened 2023-01-13 10:22 UTC
# Problem/Motivation
No connection to home assistant for the sensor nodes etc

> (Why the issue was filed)

## Expected behavior
connection to server

> (What you expected to happen)

## Actual behavior
home assistant nodes show as disconnected

> (What actually happened)

## Steps to reproduce
viewable in the nodered dashboard as disconnected under each home assistant node

> (How can someone else make/see it happen)
connected with 2023.1.1, connection fails with updates since then including 2023.1.4

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
rollback to 2023.1.1 was the only fix.  i rolled back to 2023.1.2 - that didnt work

**Comment by magiva** [comment] 2023-01-13 10:28
Current version: 14.0.1
Dashboard: 3.3.1
node-red-contrib-home-assistant-websocket: 0.48.0

no new updates to apply

**Comment by canedje** [comment] 2023-01-13 20:39
I did have troubles see other issues. So I decided to remove nodered addon and nodered directory to start from scratch.
I was able to startup a new Nodered addon. But not able to get nodered server connected to HA anymore. Nodered addon is now totally useless:
![image](https://user-images.githubusercontent.com/23150947/212414920-802fc428-730f-43d7-b1f2-111014eb2de4.png)

**Comment by magiva** [comment] 2023-01-14 11:56
whats mostly concerning is that i, like many and most other people, run their homes with this.  
The lack of attention these tickets get is really concerning and very disapointing.

**Comment by canedje** [comment] 2023-01-14 13:00
Yes indeed I do think exactly the same. This is already going om for a month without any reaction from anyone

**Comment by magiva** [comment] 2023-01-16 11:57
[12:54:49] INFO: Starting NGinx...
16 Jan 12:54:49 - [info] [mqtt-broker:hass-mqtt] Connected to broker: mqtt://localhost:1883
16 Jan 12:54:54 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Jan 12:54:54 - [info] [server:Home Assistant] Connected to http://supervisor/core
16 Jan 12:54:54 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Jan 12:54:54 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
16 Jan 12:54:54 - [debug] [server:Home Assistant] HA State: running
16 Jan 12:54:54 - [debug] [server:Home Assistant] Integration: notloaded

i see after changing log_level to debug, Integration is not loaded

**Comment by magiva** [comment] 2023-01-16 14:55
is anyone going to acknowledge this ticket ?

**Comment by magiva** [comment] 2023-01-16 19:27
so to move this forward.... i created a new home-assistant server connection as a manual connection.
to do this i had to click the user icon (bottom left) and create a permanent token, copy and use that

this worked to a point.
it connected and most things were back up and working.  except the integration only sees some, not all entities !!!!

so some of the entities i had as triggers now are not found.  Its a rediculously bad piece of code that frustrates me alot.
maybe you have more luck.

the other way round is to create automations to post mqtt and have mqtt listeners in nodered.

**Comment by canedje** [comment] 2023-01-16 19:55
I do run a seperate docker under Unraid with NR. And did as backup in HA the same you mentioned.
Make a new server straight to de HA IP with a token
My only problem is dat NR flows are slower now. Especially when Zwave is used

**Comment by magiva** [comment] 2023-01-16 20:47
just create a new ha server entry and don't tick the box to use ha
integration

let me know if you need more info

**Comment by martinsheldon** [comment] 2023-01-18 09:53
> whats mostly concerning is that i, like many and most other people, run their homes with this. The lack of attention these tickets get is really concerning and very disapointing.

I totally agree with you on this. I really appreciate the effort the team are putting in to developing HA but with several people experiencing this issue we should expect an update or at least know if they are aware and working on it. After all Node Red is the 6th most popular addon accoring to their own analytics page with 34 000 installs.

As a temporary workaround I've moved my NR to Docker in Unraid and that has been working fine for over a week. However, this is not how I prefer to do it as a long term solution.

**Comment by roybosch** [comment] 2023-01-20 11:05
> a temporary workaround I've moved my NR to Docker in Unraid and that has been working fine for over a w

I too agree with this. 

I found out that not all users experience the same issues. A friend of mine uses a RPI4 and didn't experience any problems with NodeRed since last update. I'm using an Odroid N2+. What hardware do you use?

I figured that maybe my Home Assistant would have become a little corrupted, because also the developer tools/status tab has very high loading times. I reinstalled Home Assistant and restored a backup to find out that none of it mattered. It didn't resolve any of it.

**Comment by magiva** [comment] 2023-01-20 11:12
mine is both a pi and vmware ha os.
its more that not one person has been assigned any of the tickets.

**Comment by martinsheldon** [comment] 2023-01-23 06:25
> > a temporary workaround I've moved my NR to Docker in Unraid and that has been working fine for over a w
> 
> I too agree with this.
> 
> I found out that not all users experience the same issues. A friend of mine uses a RPI4 and didn't experience any problems with NodeRed since last update. I'm using an Odroid N2+. What hardware do you use?
> 
> I figured that maybe my Home Assistant would have become a little corrupted, because also the developer tools/status tab has very high loading times. I reinstalled Home Assistant and restored a backup to find out that none of it mattered. It didn't resolve any of it.

I'm using an old Dell Laptop to run Unraid but I've testet with two laptops and both Unraid and Proxmox with exactly the same behaviour.

States tab in Dev tools is also super slow for me. I mentioned this in the WTH month in October and I believe it was Frenck that commented this indeed was something they was interested in improving so I think its a general issue when you have lots of entities.

**Comment by roybosch** [comment] 2023-01-23 08:42
> States tab in Dev tools is also super slow for me. I mentioned this in the WTH month in October and I believe it was Frenck that commented this indeed was something they was interested in improving so I think its a general issue when you have lots of entities.

I guess so. But I didn't have this problem before, and I didn't add entities since the last update. Even so the performance dropped drastically.

**Comment by canedje** [comment] 2023-01-23 09:25
I agree with above message.
It suddenly appeared without changes.
Communication with HA is slower in general

**Comment by natedzl** [comment] 2023-01-23 12:26
I've been having a similar experience and have been struggling to get to the root cause.  Biggest issue is the delay now to zwave network from NR.  I've rolled back to 2023.1.1 and rolled back NR and ZWave JS UI add-ons to around the same time and it's slightly better but nowhere near where it was.  I'm still showing a number of disconnects and it will eventually reconnect but not for very long.

This is very disappointing that no one is acknowledging these issues.

Running on HA Blue (Odroid N2+)

HomeAssistant - 2023.1.1
Supervisor - 2022.12.1
Operating System - 9.4
ZWave JS UI - 1.4.2
Node-Red - 14.0.1


23 Jan 03:49:26 - [info] [server:Home Assistant] Connecting to http://supervisor/core
23 Jan 03:49:26 - [info] [server:Home Assistant] Connected to http://supervisor/core
23 Jan 05:43:18 - [error] [api-call-service:Nate Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Colleen Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Noah Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Valerie Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Katelynn Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Nate Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Colleen Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Noah Home] Call-service error. 
23 Jan 05:43:19 - [error] [api-call-service:Valerie Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Katelynn Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Nate Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Colleen Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Noah Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Valerie Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Katelynn Home] Call-service error. 
23 Jan 05:43:20 - [error] [api-call-service:Nate Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Colleen Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Noah Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Valerie Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Katelynn Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Nate Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Colleen Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Noah Home] Call-service error. 
23 Jan 05:43:21 - [error] [api-call-service:Valerie Home] Call-service error. 
23 Jan 05:43:22 - [error] [api-call-service:Katelynn Home] Call-service error. 
23 Jan 05:43:22 - [error] [api-call-service:Kids Home] Call-service error. 
23 Jan 05:43:22 - [error] [api-call-service:Kids Home] Call-service error. 
23 Jan 05:43:22 - [error] [api-call-service:Kids Home] Call-service error. 
23 Jan 05:43:22 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
23 Jan 05:43:22 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
23 Jan 05:43:23 - [error] [api-call-service:Turn Off Basement Porch Lights] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off - Back Yard Sconces] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off Basement Porch Lights] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off - Back Yard Sconces] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off Basement Porch Lights] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off - Back Yard Sconces] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off Basement Porch Lights] Call-Service attempted without connection to server.
23 Jan 05:43:23 - [error] [api-call-service:Turn Off - Back Yard Sconces] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Nate Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Colleen Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Noah Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Valerie Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Katelynn Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Nate Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Colleen Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Noah Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Valerie Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Katelynn Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Nate Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Colleen Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Noah Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Valerie Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Katelynn Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Nate Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Colleen Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Noah Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Valerie Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Katelynn Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Nate Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Colleen Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Noah Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Valerie Home] Call-Service attempted without connection to server.
23 Jan 05:43:25 - [error] [api-call-service:Katelynn Home] Call-Service attempted without connection to server.
23 Jan 05:43:28 - [info] [server:Home Assistant] Connecting to http://supervisor/core
23 Jan 05:43:29 - [info] [server:Home Assistant] Connected to http://supervisor/core

**Comment by roybosch** [comment] 2023-01-27 13:08
Unfortunately the latest supervisor update doesn't fix anything. I'm still having NodeRed connect and disconnect every second.

**Comment by canedje** [comment] 2023-01-27 21:35
Yes very frustrating that there is no reaction at all for more than a month.
We don’t know the reason is also an answer. At least showing they take it seriously

**Comment by canedje** [comment] 2023-01-28 11:35
It looks like that the last operating system 9.5 did the trick.
My NodeRed is oerating normal again :-)

**Comment by roybosch** [comment] 2023-01-28 12:06
No luck for me unfortunately.

**Comment by natedzl** [comment] 2023-01-28 12:07
No luck here either - 9.5 didn't change anything for me.

**Comment by frenck** [comment] 2023-01-31 12:15
duplicate of #1498

**Closed by frenck** 2023-01-31 12:15 UTC
