### ISSUE TITLE
Nodered dashboard isn't showing up

### ISSUE THREAD

**Issue by Slayerrulez** [hassio-addons/addon-node-red#194] opened 2019-04-16 10:46 UTC
# Problem/Motivation

> No dashboard is showing up on http://<ipadress>:1880/ui

## Expected behavior

> Showing a nice dashboard with meters, numbers, gauges, etc..

## Actual behavior

> The website keeps loading forever, blank white screen

## Steps to reproduce

> Upgrading from 2.0.1 to 3.0.0

## Proposed changes

> Workaround or fix to show dashboard again

**Comment by sretalla** [comment] 2019-04-16 13:48
I think this may have been caused in some attempt to fix #190 

When starting the add-on, I see the following repeated many times in the logs before the add-on finally gives up and just stops.

```
[15:38:23] INFO: Starting Node-RED...

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Error loading settings file: /etc/node-red/config.js
TypeError: Cannot set property 'page' of undefined
    at Object.<anonymous> (/etc/node-red/config.js:48:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/node_modules/node-red/red.js:119:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
[15:38:24] INFO: Starting Node-RED... 
```

A reinstall of the add-on with default config produces the same result

**Comment by sretalla** [comment] 2019-04-16 14:18
My error... this was all due to setting dark_mode to true.

the page property is related to the editor object defined in config.js

**Comment by Shadowpheonix** [comment] 2019-04-16 15:55
Assuming this is the same issue I am experiencing, the report needs some additional clarification...

The user interface created using the [Node-Red Dashboard](https://flows.nodered.org/node/node-red-dashboard) module for Node-Red is not accessible after upgrading from to v3 of the Home-Assistant Node-Red Addon.  With the older v2 version, this user interface was accessible at http://&lt;node-red server&gt;:1880/ui.

**Comment by sickidolderivative** [comment] 2019-04-16 16:31
I can confirm the issue after the 3.0 upgrade with Hassio 0.91.3

**Comment by GShuttleworth** [comment] 2019-04-16 17:45
I can also confirm. Node Red dashboard doesn't load with latest releases.
Node Red 3.0.1
Home Assistant (Hass.io) 0.91.4

**Comment by jelkinsiv** [comment] 2019-04-17 04:05
I can also confirm. I was able to view the UI if I uninstall and reinstall. The UI will work the first time, but if you navigate away and come back, no UI.

Node Red 3.0.1
Home Assistant (Hass.io) 0.91.4

**Comment by Routout** [comment] 2019-04-17 07:02
Same issue here. ui is working only when accessed first time after install. When navigated away and back it loads only top bar.
Hass.io 32bit 0.91.4
NodeRed 3.0.1

**Comment by stefangries** [comment] 2019-04-17 13:47
Can confirm this in Opera (same engine as Chrome), but for me it's working correctly in Firefox.

**Comment by x9daniel** [comment] 2019-04-17 16:44
For me it looks like that:
- works fine in Firefox
- worked only for a first time in Chrome
- works only for a first time when using Chrome in incognito mode - after Chrome incognito restart, again works for a first time only

Here is my Chrome console log when it does not work:
```
polaris/:83 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/vendor/vendor.js net::ERR_INVALID_HTTP_RESPONSE
polaris/:84 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/vendor/jsonata/jsonata.min.js net::ERR_INVALID_HTTP_RESPONSE
polaris/:87 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/red/red.min.js net::ERR_INVALID_HTTP_RESPONSE
polaris/:86 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/vendor/ace/ext-language_tools.js net::ERR_INVALID_HTTP_RESPONSE
polaris/:85 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/vendor/ace/ace.js net::ERR_INVALID_HTTP_RESPONSE
main.min.js:16 Uncaught ReferenceError: $ is not defined
    at VM337 main.min.js:16
(anonymous) @ main.min.js:16
polaris/:57 GET http://polaris:8123/api/hassio_ingress/D4VKfR76eJWaNoLIGANeI8c6qZoZO-dAD62Xyc1RsO4/red/images/spin.svg net::ERR_INVALID_HTTP_RESPONSE
```

**Comment by sickidolderivative** [comment] 2019-04-17 20:42
The new ingress feature seems to be the reason: 
https://community.home-assistant.io/t/introducing-hass-io-ingress/

**Comment by nellering** [comment] 2019-04-18 17:25
On the Node Red config page (from the Hassio tab, there is a new Network section below the configuration section.  My eyes skipped over this originally.   Change the setting from “disabled” to “1880” and it will work again.

**Comment by Routout** [comment] 2019-04-18 17:33
It is intented to work like that? Why it's working first time but not after that?

**Comment by nellering** [comment] 2019-04-18 17:34
You might have had it cached and then it goes away once it tries to pull the page that isn’t there.  It happened to me also.

**Comment by Routout** [comment] 2019-04-18 17:58
> You might have had it cached and then it goes away once it tries to pull the page that isn’t there. It happened to me also.

Doesn't work for me on Chrome.

> On the Node Red config page (from the Hassio tab, there is a new Network section below the configuration section. My eyes skipped over this originally. Change the setting from “disabled” to “1880” and it will work again.

Doesn't work for me on Chrome.

**Comment by jelkinsiv** [comment] 2019-04-18 18:03
I was able to get it work...kinda. @nellering post game me an idea. In chrome if you open the UI and you just get the banner, try this.

1. Right click and select 'Inspect' from the menu.
2. Go back to the browser/tab with HA, right click the refresh button and select 'Empty Cache and Hard Reload'

Doing this refreshes page, and at least for me, the UI displays again on reload. If you navigate away you do need to repeat the steps.

**Comment by SNoof85** [comment] 2019-04-19 20:26
Step from @jelkinsiv worked for me.
Console from Chrome gives this when UI is not showing : 
```
64The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
58service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
:8123/manifest.json:1 Manifest: property 'theme_color' ignored, 'hsl(var(--huesat) 40%)' is not a valid color.
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
vendor.js:1 Failed to load resource: net::ERR_FAILED
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
jsonata.min.js:1 Failed to load resource: net::ERR_FAILED
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
spin.svg:1 Failed to load resource: net::ERR_FAILED
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
ace.js:1 Failed to load resource: net::ERR_FAILED
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
ext-language_tools.js:1 Failed to load resource: net::ERR_FAILED
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
red.min.js:1 Failed to load resource: net::ERR_FAILED
main.min.js:16 Uncaught ReferenceError: $ is not defined
    at main.min.js:16
```

**Comment by frenck** [comment] 2019-04-22 15:50
This issue has been addressed and resolved in the `v3.0.2` release of the add-on.

Thanks for reporting the issue 👍

**Closed by frenck** 2019-04-22 15:50 UTC

**Comment by kandbcontrols** [comment] 2019-05-02 01:58
I just upgraded to 3.0.3 and this is happening to me.

**Comment by kandbcontrols** [comment] 2019-05-02 13:34
When i try to open the dashboard now, a new tab in chrome opens like before, but I get page
404: Not Found

**Comment by usenetj23** [comment] 2019-05-02 21:15
if I add 1880 port and go to :1880/ui/#!/0 or Node-Red admin page it asks user and password. None is working. Added adminAuth to settings.js - nothing helps. Password generated with 
node-red-admin hash-pw

**Comment by keithajohnson** [comment] 2019-05-04 13:45
This is happening for me as well. I'm in an endless http password prompt loop (incognito or not) for the UI. I can access the node red interface at `[HA IP]:[nodered port]` after entering my password, but the same doesn't work for `[HA IP]:[nodered port]/ui`.

Node Red: v3.0.3
HA: 0.92.0

**Comment by kandbcontrols** [comment] 2019-05-04 20:16
Yeah, I can not get the dashboard to come up no matter what I try. I've
tried disabling ingress mode with putting port 1880 in the config and 9000.
It acts the same way as ingress mode. I don't know if it's doing anything.
I have gotten node red to open in a new tab full screen by accident trying
to get the UI to open by right clicking on the dashboard tab and clicking
open in a new tab. However nothing gets the dashboard to work. Everything
I've tried gives me error 404: not found. The dashboard is where I have my
keypad for my alarm,  so it's not good.  Some how I think Frenck thinks I
am trying to get the dashboard to work in ingress mode. I know it doesn't
work, I just don't know how to disable it. He has not responded. He just
closed the issue. I'm sorry if I upset him. I didn't mean to. He probably
gets alot of stupid questions.

**Comment by Def3nder** [comment] 2019-05-10 09:20
Why is the issue closed ?
Did an upgrade from 2.0.2 to 3.0.3 and have the same issue as described here: DASHBOARD NOT SHOWING.

The dashboard - Link is: "http://Hassio-Adress:8123/ui"
Get an Error 404 instead of the dashboard.

If I change the port to 1880, I get asked User / Password, but none of the configurred ones do work.

Please re-open the issue (as it is not solved yet).

Thanx,
Ralf

**Comment by markrgriffin** [comment] 2019-05-12 19:18
Tried the 'fixes' in the posts above but to no avail. Still getting a new login/password box after filling in the 1st box and not getting into ui.
Any help would be appreciated

**Comment by kandbcontrols** [comment] 2019-05-12 19:48
I've been out of town all week, but from what I can tell there has been no
response about this. I'm not even sure Frenck is seeing this. This whole
ordeal has been very frustrating for me. I feel like I was just blown off
when I reported this 8 or 9 days ago. This sure isn't what I think of when
I hear community. Many places that I have read on forums go out of there
way to help. Really has me reconsidering my use of this going forward.

**Comment by HenkSnavel** [comment] 2019-05-21 20:49
It changed for me when I went to node-red 3.1.0 For me, it’s now https://*.duckdns.org:1880/endpoint/ui/#!/0

**Comment by artpcpl** [comment] 2019-05-25 14:58
> HenkSnavel` thx for help > user and pass from hass.io Config  nodered

**Comment by arnoldpistorius** [comment] 2019-06-24 05:26
This is not working for me as well. I use remote.nabucasa.com to access my home assistant installation remotely. However via http://internalip:1880/endpoint/ui it is working fine. Also the http input node isn't working from home assistant (ingress).

**Comment by arretx** [comment] 2019-06-27 00:57
I _was_ having difficulty with this but just managed to get the /ui to load.  My setup:

HASS.io, NodeRED Add-on 4.0.1, Ubuntu 16.04, Docker

Ingress fails.  I still get 502 Bad Gateway, so to get to the NodeRED **editor**, I have to go to http://serverip:1880 directly, then login with HA user credentials.

**However**: to load the NodeRED UI  _**Dashboard**_, I had to go to `http://serverip:1880/endpoint/ui` and use the user name and password that I defined in the NodeRED Add-On configuration.  The section that reads `http_node` and `http_static`

~~~
{
  "credential_secret": "blahblahblah",
  "dark_mode": true,
  "http_node": {
    "username": "!secret red_username",
    "password": "!secret red_password"
  },
  "http_static": {
    "username": "!secret red_username",
    "password": "!secret red_password"
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}
~~~

After using that, it loaded right away.

**Comment by arnoldpistorius** [comment] 2019-06-27 05:58
Any ideas to make this work with nabucasa remote URLs as well? Node red loads fine, but can't access the dashboard on this URL: https://myid.ui.nabu.casa/a0d7b954_nodered/endpoint/ui
