### ISSUE TITLE
Node red won't start

### ISSUE THREAD

**Issue by theSC** [hassio-addons/addon-node-red#330] opened 2019-10-05 15:49 UTC
# Problem/Motivation

Addon won't fully start. Get's caught in a loop

## Expected behavior

Addon starts

## Actual behavior

Addon won't start

## Steps to reproduce

This is a 100% new fresh install in ProxMox with only the SSH addon also installed

## Proposed changes

I have no idea.

Here is the section of the log that loops:

[08:47:12] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
5 Oct 08:47:32 - [info] 
Welcome to Node-RED
===================
5 Oct 08:47:32 - [info] Node-RED version: v0.20.8
5 Oct 08:47:32 - [info] Node.js  version: v10.16.3
5 Oct 08:47:32 - [info] Linux 4.19.72 x64 LE
5 Oct 08:47:38 - [info] Loading palette nodes
5 Oct 08:47:58 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
5 Oct 08:48:01 - [info] Dashboard version 2.16.3 started at /endpoint/ui
5 Oct 08:48:05 - [info] Settings file  : /etc/node-red/config.js
5 Oct 08:48:05 - [info] Context store  : 'default' [module=memory]
5 Oct 08:48:05 - [info] User directory : /config/node-red/
5 Oct 08:48:05 - [warn] Projects disabled : editorTheme.projects.enabled=false
5 Oct 08:48:05 - [info] Flows file     : /config/node-red/flows.json
5 Oct 08:48:06 - [info] Starting flows
5 Oct 08:48:06 - [info] Started flows
5 Oct 08:48:06 - [info] Server now running at http://127.0.0.1:46836/
5 Oct 08:48:11 - [red] Uncaught Exception:
5 Oct 08:48:11 - TypeError [ERR_INVALID_OPT_VALUE]: The value "4294967295" is invalid for option "family"
    at lookup (dns.js:112:11)
    at net.js:1003:5
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at lookupAndConnect (net.js:1002:3)
    at Socket.connect (net.js:937:5)
    at Object.connect (net.js:156:17)
    at Object.netConnect [as createConnection] (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:659:14)
    at new ClientRequest (_http_client.js:255:33)
    at request (http.js:42:10)
    at get (http.js:46:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-05T15_48_11_741Z-debug.log
[08:48:12] INFO: Starting Node-RED...

**Comment by sinclairpaul** [comment] 2019-10-05 16:02
What OS are you running, it would appear to me that it cannot communicate/resolve the Homeassistant container, so it looks like a name resolution issue.

**Comment by theSC** [comment] 2019-10-05 16:03
It's HassOS.  Installed with this script
https://github.com/whiskerz007/proxmox_hassos_install

**Comment by sinclairpaul** [comment] 2019-10-05 16:15
In all honesty the issue isn't with the addon itself `at Object.netConnect [as createConnection] (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:659:14)`

I would check at https://github.com/zachowj/node-red-contrib-home-assistant-websocket to see the source of the error, however I do believe its likely name resolution related

**Comment by theSC** [comment] 2019-10-05 16:40
DNS seems fine. I can ping out no problem.  

Check home-assistant-websocket? Not sure where I would start to look into that.
Doesn't this addon ship with home-assistant-websocket out of the box?

**Comment by sinclairpaul** [comment] 2019-10-05 16:42
The link to the repo is in my previous comment.  From the log Node Red is starting and running and that component is throwing the error, which yes is bundled.

**Comment by theSC** [comment] 2019-10-05 16:43
I saw the link but not sure how that would help me. I see nothing in the issues there related to my problem. Unless you are saying to post my issue there

**Comment by theSC** [comment] 2019-10-05 16:47
Node red does start for a second or two (Can't reach the webUI at all though) but then when this error is thrown it starts over again and just loops like that

**Comment by sinclairpaul** [comment] 2019-10-05 23:34
Yes please post your issue there to determine root cause.  The add on functions and starts Node-Red, so I will close this out.

**Closed by sinclairpaul** 2019-10-05 23:34 UTC
