### ISSUE TITLE
Time Zone settings in NodeRed

### ISSUE THREAD

**Issue by matt1as** [hassio-addons/addon-node-red#58] opened 2018-10-20 06:57 UTC
# Problem/Motivation

I'm trying to use a inject node to trigger a flow, but the specific time setting need to be in UTC and not my local time zone. Debug output shows timestamp in UTC

## Expected behavior

Node to be triggered at the correct time according to my time zone settings. 

## Actual behavior

Node triggered at the UTC time. I assume the docker image has the TZ set to UTC 

## Steps to reproduce
Create Node flow with Inject Node and connect it to a debug node
Set time 2 minutes into future 
Wait - nothing

Create Node flow with Inject Node and connect it to a debug node
Set time 2 minutes into future UTC time 
Wait
Inject node triggers and writes the current timestamp as message

## Proposed changes

~Add setting in plugin settings to set Timezone~
Inherit setting from Home Assistant configuration
```
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones0
  time_zone: Europe/Stockholm
```

**Comment by matt1as** [comment] 2018-10-21 06:28
> same issue for me. Using UTC, my home assistant time is correct, this seems to be related to [Node-Red #48](https://github.com/node-red/node-red-docker/issues/48).

Yes, but I hope the plugin somehow can take advantage of the existing home assistant setting

**Comment by frenck** [comment] 2018-10-21 18:02
I think I could provide an additional option for you guys to override the timezone for the add-on. Is that something plausible?

**Comment by frenck** [comment] 2018-10-29 22:17
I was not able to reproduce this issue.
Add-on version 1.0.0 got out, could you please test it with that version?

**Comment by matt1as** [comment] 2018-10-30 10:06
I cannot reproduce it either anymore. Not sure if 1.0.0 solved it, or if I did something in my flows (I've recreated all flows started from an Inject Node.

**Comment by frenck** [comment] 2018-10-30 11:11
OK, I'll close this issue for now. Feel free to re-open or create a new one if the issues pop up again.

**Closed** 2018-10-30 11:12 UTC
