### ISSUE TITLE
Access Logs spaming Log Output

### ISSUE THREAD

**Issue by niklasfink** [hassio-addons/addon-node-red#863] opened 2021-01-24 09:57 UTC
# Problem/Motivation

The log output of the node-red plugin is being spammed by the access logs which ignore the log_level setting. It doesn't matter what log_level is being set, hundreds of access logs are being posted. That makes debugging node-red a hard thing to do.

Example:
[24/Jan/2021:10:48:54 +0100] 200 192.x.x.x, 172.x.x.x(172.3x.x.x) GET /icons/node-red/cog.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.04 Safari/537.36)

## Expected behavior

Access logs are only being logged if configured in the configuration. Example by setting "access_logs: true" or using the node-red audit config setting. https://nodered.org/docs/user-guide/runtime/logging#audit

## Actual behavior

Access logs are being logged regardless of any log_level setting.

## Steps to reproduce

Install HassOS. Install Node-Red Plugin in Supervisor. Set log_level to "info" or "warning". See log being spammed.

## Proposed changes

Introduce "access_logs:" configuration option.

**Comment by frenck** [comment] 2021-01-24 11:23
> That makes debugging node-red a hard thing to do.

Depends on what one is debugging 😉 

The setting is a debug log level setting for the add-on logic, so that might not be clear.

As for the wish of handling access logs, the access log you see are not from Node-RED, thus the link provided for logging auth, doesn't make sense here.

As this is not a bug, but a feature request, I'm moving this over to discussions.

**Comment by niklasfink** [comment] 2021-01-24 13:54
I see, fair enough. 

When creating this feature request, I'd also add "consistent coloring of logs".

When the Node-RED plugin is starting, coloring works. However, as soon as it is running, the some other kind of logging comes in place and the coloring doesn't work anymore. The example below is both written in black, which makes errors harder to detect. 🙂 

[24/Jan/2021:13:47:30 +0000] 200 192.x.x.x, 172.x.x.x(172.x.x.x) GET /icons/node-red-contrib-virtual-smart-home/vsh_icon.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0 Safari/537.36)
24 Jan 14:47:35 - [error] [api-call-service] Call-service API error. Error Message: Service not found.
[24/Jan/2021:13:47:45 +0000] 101 192.x.x.x, 172.x.x.x(172.x.x.x) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0 Safari/537.36)

**Comment by frenck** [comment] 2021-01-24 13:56
Same story, the output from different programs is shown. It is up to that software to decide how to output it (including color).

Feel free to request unity with all these programs upstream:

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/Dockerfile#L26-L32>

That request is not fixable from an add-on perspective.

**Comment by niklasfink** [comment] 2021-01-24 16:24
Thanks for explaining and keep up the great work! This ticket can then be closed, or cloned into a feature request.

**Comment by trickiegt** [comment] 2021-01-24 16:51
I think this is similar but not quite the same as what niklas is dealing with.  I had issues yesterday after the update with the server 500 error.  Got the next update today and now my log files spam authentication lines multiple times a second and is making my supervior ram usage surge.

`
21-01-24 16:46:14 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:14 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:14 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:14 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:15 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:16 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
21-01-24 16:46:17 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:17 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:17 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:17 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Auth request from 'a0d7b954_nodered' for '#UserName#'
21-01-24 16:46:19 INFO (MainThread) [supervisor.auth] Successful login for '#UserName#'
`

**Comment by frenck** [comment] 2021-01-24 16:54
No that is not the add-on log @niklasfink but the supervisor log. Please report supervisor issues upstream, thanks! 👍

**Closed** 2021-02-03 08:46 UTC
Labels: priority-low
