### ISSUE TITLE
Nodered refused credentials when connecting through port

### ISSUE THREAD

**Issue by inputd** [hassio-addons/addon-node-red#191] opened 2019-04-15 13:17 UTC
# Problem/Motivation

Updated to latest version

## Expected behavior

When manually specifying a port, to be able to view Node-Red in a full window

## Actual behavior

Cannot log in with any hass.io credentials. Cannot login even if I specify a user/password in HTTP_node and static.

**Comment by frenck** [comment] 2019-04-15 13:18
Duplicate of #190

**Closed by frenck** 2019-04-15 13:18 UTC
