### ISSUE TITLE
problem with panel / ingress

### ISSUE THREAD

**Issue by pilot1981** [hassio-addons/addon-node-red#205] opened 2019-04-18 13:23 UTC
Hi,
I have HASSIO 0.91.4 with nodeRED 3.0.1, this is my node red config:

{
  "credential_secret": "xxxxx",
  "dark_mode": false,
  "http_node": {
    "username": "xxxxxxxx",
    "password": "xxxxxxxx"
  },
  "http_static": {
    "username": "xxxxxxxx",
    "password": "xxxxxxxx"
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [
    "node-red-admin",
    "node-red-contrib-light-scheduler"
  ],
  "init_commands": []
}

Container | Host | Description
-- | -- | --
80/tcp |  disabled  | Web interface (Not required for Hass.io Ingress)

and this panel config in configuration.yaml:

# IPANEL CONFIGURATOR HASSIO
panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
#    url: https://xxxxx.duckdns.org:1880
#    url: https://xxxxxx.duckdns.org:8123/api/hassio_ingress/a0d7b954_nodered/

I notice that after introduction of ingress in lastest version (I upgraded from older versions), I not able to access to node red using ipanel in HASSIO WEB GUI.

it's a bug or it's a problem of configuration?

**Comment by PurelyNicole** [comment] 2019-04-18 13:56
In your network configuration, you need to replace "disabled" with "1880" in Host.

I'm having an issue with Node-RED accepting my credentials when accessing it from the iPanel though. Leaving access to be from the Node-RED add on and selecting "open web UI."

**Comment by lsilva171** [comment] 2019-04-19 00:49
Same problem with me. Node-RED v3 keeps asking for credentials when accessing it from iPanel. I reverted back to v2 as it works as expected.

**Comment by pilot1981** [comment] 2019-04-19 08:03
I understood panel is deprecated, so no I have to use new ingress with a configuration similar to this:

panel_custom:
  - name: hassio
    sidebar_title: Configurator
    sidebar_icon: mdi:wrench
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: "core_configurator"


 in configuration.yaml...but I don't understand howto config node_red....

**Comment by ameennihad** [comment] 2019-04-20 07:01
I had same issue last night, I upgraded HA from 0.91.2 to 0.91.4 and Node-Red from 2.0.1 to 3.0.1, Node-Red was not accessible from OPEN WEB UI link, when I click this link only Node-Red header appears in the page, when I changed the network port to 1880 I was unable to login neither with my previous Node-Red credentials nor with my HA credentials, I tried changing my HA password but that didn't solve the issue, I had to revert back to V2.0.1.

Node-Red Addon log was not showing any issues. I'm not sure if Node-Red was working correctly, I tested only one automation while still on V3.0.1 it didn't work.

**Comment by mayankraichura** [comment] 2019-04-21 10:28
I'm having exactly the same issues as ameennihad.

**Comment by tooljose88** [comment] 2019-04-21 11:29
Try this: 
```
panel_custom:
  - name: hassio-main
    sidebar_title: Node-Red
    sidebar_icon: mdi:sitemap
    js_url: /api/hassio/app/entrypoint.js
    url_path: node-red
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_nodered
```

**Comment by geoffreys** [comment] 2019-04-22 08:45
There's a workaround for the login loop https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023/628 (dump browser local storage)

**Comment by frenck** [comment] 2019-04-22 14:20
Duplicate of #201

**Closed by frenck** 2019-04-22 14:20 UTC

**Comment by ameennihad** [comment] 2019-04-22 18:26
Clearing Local Storage solved the problem.

**Comment by PurelyNicole** [comment] 2019-04-23 11:51
Clearing local storage worked for me as well.
