### ISSUE TITLE
Not loading with Nabu Casa

### ISSUE THREAD

**Issue by nellering** [hassio-addons/addon-node-red#206] opened 2019-04-19 16:02 UTC
# Problem/Motivation

> I want to access Node Red remotely with Nabu Casa ingress session.  

## Expected behavior

> Node Red would load like it does when I am on my local network.  

## Actual behavior

> It appears like it is not loading.  It partially loads after 5 minutes.  It is not useable on Nabu Casa.  

## Steps to reproduce

> Install Node Red 3.0.1.  Login to Nabu Casa.  Click "Open Web UI" from Node Red application on HassIO tab.  

## Proposed changes

> Get Ingress working properly with Nabu Casa.  

It looks like this after ~3 minutes:
![Capture](https://user-images.githubusercontent.com/32467198/56432341-940ae500-6292-11e9-881c-7934f043ee29.PNG)

It looks like this after ~5 minutes and doesn't load more:
![Capture2](https://user-images.githubusercontent.com/32467198/56432344-9705d580-6292-11e9-8e33-0392952bfe55.PNG)

**Comment by frenck** [comment] 2019-04-22 14:19
Duplicate of #201

**Closed by frenck** 2019-04-22 14:19 UTC
