### ISSUE TITLE
Node-RED not triggering automations after Home Assistant restart

### ISSUE THREAD

**Issue by e1miran** [hassio-addons/addon-node-red#17] opened 2018-08-10 15:52 UTC
## Expected behavior

> Upon restart of Home Assistant, Node-RED is expected to handle and trigger automations.

## Actual behavior

> After re-starting Home Assistant, Node-RED fails to detect state changes of connected entities or fire automations. This is resolved by restarting the add-on.

## Steps to reproduce

> Restart Home Assistant.  

I'm currently running Home Assistant v0.75.2 and supervisor 125.  I first noticed this behavior a couple of updates ago to Home Assistant.  Restarting the Add-on resolved it.

**Comment by frenck** [comment] 2018-08-15 15:17
This is not something the add-on can provide. Node-red (or better, the NodeRED Home Assistant node), should handle disconnects.

I would suggest filing an issue with the latterly named node.

**Comment by e1miran** [comment] 2018-08-17 17:58
@forast3r I have not.

**Comment by frenck** [comment] 2018-08-17 18:37
@forast3r That restarting suggestion sounds like a terrible idea. So, no, it should not.

**Comment by forast3r** [comment] 2018-08-18 14:51
@e1miran I opened an issue, hope it helps all of us

**Comment by frenck** [comment] 2018-08-24 07:57
@forast3r  @e1miran 
Just a thought... are you guys using the new Home Assistant Auth system?

**Comment by forast3r** [comment] 2018-08-24 08:09
Yes, I'm using it since it was launched

**Comment by forast3r** [comment] 2018-08-24 08:17
When only HA is restarted I get this in node-red addon logs:
`24 Aug 10:11:44 - [warn] [api-call-service:toggle input boolean] Error calling service, home assistant api error`
`24 Aug 10:11:44 - [error] [api-call-service:toggle input boolean] Error calling service, home assistant api error`

**Comment by frenck** [comment] 2018-08-24 08:35
@forast3r At that point the logs happens in the Node-RED logs, what does the Supervisor say? (Hassio -> system -> logs)

**Comment by frenck** [comment] 2018-08-24 11:31
Thanks @e1miran

**Comment by forast3r** [comment] 2018-08-24 20:27
@frenck here you have a node-red error and the corresponding log in supervisor:
node-red:

> 24 Aug 22:21:18 - [warn] [api-call-service:toggle input boolean] Error calling service, home assistant api error
> 24 Aug 22:21:18 - [error] [api-call-service:toggle input boolean] Error calling service, home assistant api error

hassio supervisor:
> 18-08-24 20:21:18 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/input_boolean/toggle access from a0d7b954_nodered
> 18-08-24 20:21:18 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/services/input_boolean/toggle: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
> 18-08-24 20:21:18 ERROR (MainThread) [hassio.api.proxy] Error on API for request services/input_boolean/toggle`

**Comment by frenck** [comment] 2018-09-07 10:44
I currently suspect the Hassio Supervisor to be the problem in this case, since (if `http://hassio/homeassistant` is used), it should take care of it.

From the add-on perspective, there is nothing I can do, besides waiting from a solution from Home Assistant (or the plugin to re-connect).

**Comment by forast3r** [comment] 2018-09-07 14:13
Thank you for keeping us informed. 
Since I added the watchdog mechanism between node-red and HA I have only suffered an urresponsive episode with node-red automations.

**Comment by gjuncu** [comment] 2018-09-28 12:32
I'm having the same issue. Steps to reproduce:
1. Make a change in Node Red without deploying
2. Restart Hass.io
3. Click Deploy in Node RED: You'll get a message like "The server is running a more recent set of flows.
The changes include no conflicts and can be merged automatically". If you click "Review Changes" , you'll notice that the "pass" in HASS Configuration node has changed:
![image](https://user-images.githubusercontent.com/2788909/46207422-008eb880-c330-11e8-8127-2b5c156844f3.png)
If I click Merge config, apparently everything's ok but no events are sent/received to/from NodeRed to Hass.io
If I click Ignore and Deploy, then I get "Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>" error in Node-Red logs until I restart Node Red. After restart, everything works.

**Comment by frenck** [comment] 2018-09-30 11:18
@gjuncu There is no need to make such an extensive report for something that was already clear.
As stated before, there is nothing I can do, since this is not within the source code of the add-on.

I'm closing this issue as well, for that reason. Feel free to submit an issue to hassio or the home assistant node repositories

**Closed by frenck** 2018-09-30 11:18 UTC
