### ISSUE TITLE
No config file anymore after upgrading from 15.x to 16.0

### ISSUE THREAD

**Issue by dersch81** [hassio-addons/addon-node-red#1735] opened 2023-11-15 10:54 UTC
`s6-rc: info: service legacy-services successfully started

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

Error loading settings file: /etc/node-red/config.js`

**Comment by frenck** [comment] 2023-11-15 10:54
Is there more information in the logs?

**Comment by dersch81** [comment] 2023-11-15 10:56
I cutted the error part:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 15.1.1
 There is an update available for this add-on!
 Latest add-on version: 16.0.0
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
[11:44:49] INFO: Starting Node-RED...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

Error loading settings file: /etc/node-red/config.js
[11:44:50] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[11:44:50] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by DieMetRik** [comment] 2023-11-15 10:57
After update disappearing all flows

/usr/share/hassio/addons/data/a0d7b954_nodered is empty
/usr/share/hassio/addon_configs/a0d7b954_nodered with my flows?

**Comment by antro31** [comment] 2023-11-15 10:58
Same for me. 
All flows disappeared. Reverted back to previous version (+ had to restore backup of the configuration since data were lost also)

**Comment by dersch81** [comment] 2023-11-15 10:58
Seems restarting missed the new version in my log upwards, here is the actual one:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 16.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
[11:56:40] INFO: Starting Node-RED...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js

15 Nov 11:56:42 - [info] 

Welcome to Node-RED
===================

15 Nov 11:56:42 - [info] Node-RED version: v3.1.0
15 Nov 11:56:42 - [info] Node.js  version: v18.18.2
15 Nov 11:56:42 - [info] Linux 6.1.59 x64 LE
15 Nov 11:56:42 - [info] Loading palette nodes
15 Nov 11:56:44 - [info] Dashboard version 3.6.1 started at /endpoint/ui
15 Nov 11:56:45 - [info] Settings file  : /etc/node-red/config.js
15 Nov 11:56:45 - [info] Context store  : 'default' [module=memory]
15 Nov 11:56:45 - [info] User directory : /config/
15 Nov 11:56:45 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Nov 11:56:45 - [info] Flows file     : /config/flows.json
15 Nov 11:56:45 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

15 Nov 11:56:45 - [info] Server now running at http://127.0.0.1:46836/
15 Nov 11:56:45 - [warn] Encrypted credentials not found
15 Nov 11:56:45 - [info] Starting flows
15 Nov 11:56:45 - [info] Started flows
[11:56:45] INFO: Starting NGinx...
15 Nov 11:56:50 - [info] [server:Home Assistant] Connecting to http://supervisor/core
15 Nov 11:56:50 - [info] [server:Home Assistant] Connected to http://supervisor/core`

**Comment by frenck** [comment] 2023-11-15 11:00
@dersch81 That is a duplicate of #1733, which is fixed by #1734, released in v16.0.1

**Comment by Bloodpack** [comment] 2023-11-15 11:00
Same here, 

update from 15.x to 16.0, all flows gone....
restored nodered backup, addon not starting, all flows gone.......

**Closed by frenck** 2023-11-15 11:00 UTC

**Comment by antro31** [comment] 2023-11-15 11:04
@Bloodpack : You should also restore the configuration. (/homeassistant/node-red folder)

**Comment by dersch81** [comment] 2023-11-15 11:13
can we reopen this? It is not solved

**Comment by frenck** [comment] 2023-11-15 11:15
It is solved, restore a backup (don't forget to restore an HA backup, as that contains the flows), migrate from v15 -> v16.0.1 directly.

**Comment by antro31** [comment] 2023-11-15 11:17
@frenck : Migrating from 15 -> 16.0.1 did not work for me. node-red restarted with an empty flow.

**Comment by wokkeltje13** [comment] 2023-11-15 11:18
same for me, 16.0.1 removed the flows again

**Comment by dersch81** [comment] 2023-11-15 11:22
> It is solved, restore a backup (don't forget to restore an HA backup, as that contains the flows), migrate from v15 -> v16.0.1 directly.

doing a proxmox VM restore now (from 15.11.23 02:00) because my last core backup is from upgrading 11.0 > 11.1 from last week

**Comment by nivek1612** [comment] 2023-11-15 11:27
> same for me, 16.0.1 removed the flows again

And for me

**Comment by sdavides** [comment] 2023-11-15 11:33
same for me, update 👎

**Comment by dersch81** [comment] 2023-11-15 11:34
VM Restore done. But i'm afraid to do the 16.0.1 upgrade now. Seems it is not solved

**Comment by sdavides** [comment] 2023-11-15 11:45
Solved
from backup "/config/nodered/flow.json"
import flow.json
deploy

**Comment by Dsna1R** [comment] 2023-11-15 11:57
I had to restore a full backup to recover my flows. 16.0.1 does not solve the problem either. I'm staying on 15.1.1 for now.

**Comment by MarcoL1975** [comment] 2023-11-15 12:14
Updated to 16.0.1 and took my flows.json from my last HA backup from last week.... looks like it's working now

**Comment by nivek1612** [comment] 2023-11-15 12:22
> Updated to 16.0.1 and took my flows.json from my last HA backup from last week.... looks like it's working now

Good to know but I would have hoped an update coped with this without the need to do backups/restore of flows. I'll stay on 15.1.1 for now

**Comment by nivek1612** [comment] 2023-11-15 13:23
This worked for me 
But I always take a full HA backup before any changes, that backup when fully restored will correct the directory changes which I think is the issue with 16.0.0 and 16.0.1

Restore complete full HA backup taken before any upgrade to 16.0.x (overwrite everything)
Install 16.0.2
All works

**Comment by frenck** [comment] 2023-11-15 13:32
Please see #1736
