### ISSUE TITLE
PANIC: unprotected error in call to Lua API (bad light userdata pointer)

### ISSUE THREAD

**Issue by MadDoct** [hassio-addons/addon-node-red#199] opened 2019-04-17 08:26 UTC
# Problem/Motivation

Node-Red doesn't start in the new version - worked before...
> (Why the issue was filed)

## Expected behavior

It should start as normal
> (What you expected to happen)

## Actual behavior

It stops with the following error:
[09:22:40] INFO: Starting NGinx...
17 Apr 09:22:40 - [info] Starting flows
17 Apr 09:22:40 - [info] Started flows
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> (What actually happened)

## Steps to reproduce

Starting the add-on
> (How can someone else make/see it happen)

## Proposed changes

Update nginx to a version that supports aarch64...
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by deece** [comment] 2019-04-17 10:39
+1

**Comment by deece** [comment] 2019-04-18 06:00
Broken in  4f3d08b55f7fc2dcec10bb8b4c82600dec6c5d3a

The LUA module requires a patch (already in mainline), so it will have to be built from source until the Alpine packages catch up: openresty/lua-nginx-module#1379

**Comment by frenck** [comment] 2019-04-18 07:15
This is an upstream issue with Alpine.
I know the module has issues on aarch64/ARMv8/64bits ARM devices. It has been fixed in the openresty mainline in Oct 2018 and released in Feb 2019. Nevertheless, Alpine has not updated.

For the record, I'm not going to compile this in manually, because it requires more than simply compiling a module.

**Comment by deece** [comment] 2019-04-18 07:37
Can you please advise how to roll back to an older version of the addon?

**Comment by frenck** [comment] 2019-04-18 07:45
Hassio currently provides no way to do that.

**Comment by deece** [comment] 2019-04-18 08:00
I'm logging this with Alpine, but in the meantime, could you please disable this feature on aarch64 so those of us who use it can get control of our house again?

**Comment by frenck** [comment] 2019-04-18 08:01
I'm currently building a PR for the Alpine aport repository.

No I can't disable this for aarch64.

**Comment by deece** [comment] 2019-04-18 08:04
Ok, thanks, I've logged this bug report: https://bugs.alpinelinux.org/issues/10284

**Comment by frenck** [comment] 2019-04-18 08:05
Your upstream bug report is incorrect, but thanks.

**Comment by deece** [comment] 2019-04-18 08:46
Dupe of #193

**Comment by frenck** [comment] 2019-04-18 09:38
@deece 

https://github.com/alpinelinux/aports/pull/7121
https://github.com/alpinelinux/aports/pull/7122

**Comment by deece** [comment] 2019-04-18 11:09
Awesome, thankyou :)

**Comment by frenck** [comment] 2019-05-07 11:28
Upstream has been fixed (Alpine) and even backported to Alpine 3.9.
The development branch Node-RED has been updated, will be fixed in the next add-on release.

**Comment by charlietomo** [comment] 2019-05-11 07:44
@frenck do you have an estimate of when the next release will be? Thanks

**Comment by frenck** [comment] 2019-05-11 07:48
I don't work on a schedule.

**Comment by charlietomo** [comment] 2019-05-12 23:26
> I don't work on a schedule.

Understood, but an estimate of time quantum (days/weeks/months) would help those of us who rely on Node-Red to make a decision on the way forward. I've just moved from RaspberryPi to Odroid C2 and (unintentionally) moved from 32 to 64bit, which is causing a bunch of problems with add-ons related to `unprotected error in call to Lua API`. If this is a long term problem I will spin up Node Red elsewhere in order to get my setup working again - but that is a sub optimal solution.

I am making the assumption there is nothing I as a non programmer can do to help expedite this; if there is, please say.

**Comment by frenck** [comment] 2019-05-18 12:26
@charlietomo Several months.

**Comment by frenck** [comment] 2019-05-18 19:02
Fixed in release v3.1.0

**Closed by frenck** 2019-05-18 19:02 UTC

**Comment by agoralive** [comment] 2019-05-18 19:45
When will this be available in the hass.io? I still only see v3.0.3

**Comment by frenck** [comment] 2019-05-18 19:46
@agoralive It is already there.
Maybe your Hass.io instance didn't pick it up yet (can take up to 8 hours).
You can force it, by going into the Hass.io panel -> Add-on store -> Click the refresh icon in the top right.

**Comment by sinclairpaul** [comment] 2019-05-18 19:46
Refresh the addon store (top right corner), it is available now.

**Comment by charlietomo** [comment] 2019-05-19 23:17
Thanks for the update, this now runs on my Odroid C1.
