### ISSUE TITLE
NPM Packages are LOADED instead of INSTALLED.

### ISSUE THREAD

**Issue by tethlah** [hassio-addons/addon-node-red#1721] opened 2023-10-29 12:06 UTC
# Problem/Motivation

In the config there is an option for NPM packages to be installed.  It appears as though this is doing a fresh install every time the addon starts up.  If the internet goes out the addon fails to start because it can't install the packages.  I wouldn't call this an install as every time the addon starts up it's doing a new install, this is more like loading the packages.  Having an automation server that cannot run because the internet goes out defies the logic of localization by making your entire workflow dependent on on an internet connection.  Having 100% of your automations go down because a single package cannot be installed is a single point of failure which should be avoided at all costs.  Permanent storage of an installed package is not only reasonable, but expected.

## Expected behavior

I would expect that when the package is installed, it be permanently stored (aka installed) on the machine to be accessed even if the addon restarts with the internet down.

## Actual behavior

The packages are being installed at run time EVERY time the addon is started, this means that you if don't have internet, the addon cannot start up.

## Steps to reproduce

Have a package listed in the npm_packages option, disconnect your internet, and then start the addon.  The addon will never start.

## Proposed changes

Any packages listed in the packages options should follow this basic workflow:

If a package is listed, check if the package is already installed.
-  If NOT installed, then attempt to install it to a permanent storage space (config/node-red/packages or share/node-red/packages would be a good spot)
-  If IS installed, then attempt to update it.
-  If either of these fail, start the addon anyway with an error and the user is responsible for handling missing dependencies in their flows.

**Comment by frenck** [comment] 2023-10-29 14:24
> It appears as though this is doing a fresh install every time the addon starts up

Correct, this is documented as well.

> If the internet goes out the addon fails to start because it can't install the packages. 

Correct.

>  wouldn't call this an install as every time the addon starts up it's doing a new install

🤷 Still install in your own second part of the sentence as well.

> Having an automation server that cannot run because the internet goes out defies the logic of localization by making your entire workflow dependent on on an internet connection

Sorry, it sounds like this add-on isn't a match for you in this case.

Closing this issue, as it not an issue but by design of this add-on and at this point mostly a feature request.

../Frenck

**Closed by frenck** 2023-10-29 14:24 UTC

**Comment by tethlah** [comment] 2023-10-29 16:18
So you are hamstringing your own addon by design or just indignance?  You are the first and only programmer I've every seen that insists on reloading installations on every startup.  It's one thing if you are running a web application that can only be accessed via the internet, but these are home installations that can be ran on networks separated from the internet.

I don't know if you read what you wrote, but you literally just said you designed your project to fail to start on purpose if someone is using a feature of your program and there's an internet outage.  So instead of having any sort of error handling and allowing the program to proceed like a normal programmer would, you are saying "I use single points of failure on purpose and it fails by design".  You're right, stupid programming isn't for me.

I guess I should be honored as you at least took the time to post a request given that the previous people who have complained about this you just let it go stale and closed it with no response.  I would think that would be a clue but based on your response I can see why it's not.

**Comment by N3rdix** [comment] 2023-11-02 07:52
I agree to certain extent, I sounds more logical to only install the packages if they are not yet installed or outdated. But technically i could imagine it's some work as we are talking about docker here and the dependencies are not persisted to a volume which survives restarts... Maybe it's doable by mapping the npm cache to such a volume, but I am not enough expert to judge.

I disagree when it comes to the startup of the addon. Any error while starting up should not be ignored, regardless if it's just one missing package as in your case or any other (maybe more severe) issue.

**Comment by tethlah** [comment] 2023-11-02 09:15
> I agree to certain extent, I sounds more logical to only install the packages if they are not yet installed or outdated. But technically i could imagine it's some work as we are talking about docker here and the dependencies are not persisted to a volume which survives restarts... Maybe it's doable by mapping the npm cache to such a volume, but I am not enough expert to judge.

Very true.  Only thing I can say to that though is that he's temporarily storing npm packages (including nodes) to be loaded every time.  HOWEVER, if you install a node using palette manager from within node red, then node red will permanently store any npm packages that are dependencies for those nodes in config/node-red/node_modules.  So node red WILL permanently store npm packages in the config directory if you use package manager.  So you can use any of those packages in his settings config within node red and require them as libraries globally for your function nodes.  The only npm packages that are not permanently stored are when you are trying to require them without having something palette manager has installed that adds those npm packages.

I guess one way to get around this is to write a node with the packages you want as dependencies, publish it, install the node via palette manager, and now it's permanent so if the internet goes out you're not just left hanging.  Personally, nothing inside my network requires the internet in order to do it's job, the internet is a tool to get information, it's not a lock to open or close internal network functionality.

But I've never created a custom node, so I don't know if this is possible or not, I'm just spitballing.  But I am pointing out that node red DOES permanently install npm packages despite it being in a docker container even if the addon author refuses to on startup.

> I disagree when it comes to the startup of the addon. Any error while starting up should not be ignored, regardless if it's just one missing package as in your case or any other (maybe more severe) issue.

I'm not saying to ignore the error, I'm saying to catch the error and handle it.  He's just throwing the error and terminating.  If you can't download a package or something that used in a single node, then the entire program shouldn't just die.  Just that node should loose functionality.  So if any of the require statements cannot be met, those errors should be caught and then within node red it's up to the user to write their functions to handle the missing requirement when they access the global variable.  This way 100% of your functionality doesn't go away because a single node doesn't have something it needs.

**Comment by N3rdix** [comment] 2023-11-10 11:23
Maybe https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/ will help in future to achieve what you're looking for once it has been added to this addon.
See #1729...

**Comment by frenck** [comment] 2023-11-10 12:55
@N3rdix That is absolutely unrelated. Seems like you are not understanding what that change entails.

**Comment by N3rdix** [comment] 2023-11-10 13:04
Then I did not read it well enough I fear, thanks for clarification Frenck.

**Comment by tethlah** [comment] 2023-11-10 13:41
What I ended up doing was writing a contrib library and installed it using node red.  Since node red is actually writing packages to a shared directory permanently, I'm just putting everything I want into a node and it's being permanently saved so if node red restarts without an internet connection, the libraries are still available and the entire addon doesn't crash.

Sometimes you just have to find a workaround.  Obviously having the addon crash over the lack of an internet connection isn't acceptable, so doing it this way ensures a single point of failure can't take out my entire automation system.  Eventually I'll migrate node-red to it's own server (I have everything connected to node-red and home assistant separately, so if HA is restarting or has an issue my automations and voice commands still work, or if node-red is experiencing an issue I can still use HA to use my devices).

Having everything  integrated into home assistant as addons is convenient, but sometimes convenience comes at the cost of availability and stability.
