### ISSUE TITLE
hassio Domain not available in api-call-service

### ISSUE THREAD

**Issue by mrosseel** [hassio-addons/addon-node-red#99] opened 2018-12-25 15:52 UTC
# Problem/Motivation

I want to automate my hassio backups by calling the service: hassio.snapshot_full

## Expected behavior

In the 'api-service-call' node config screen, I expect 'hassio' to be one of the available Domains (next to lights, homeassistant, ...)

## Actual behavior

all domains are there but no 'hassio'

## Steps to reproduce

- Filter the nodes in the pallette with the word 'service'
- Drag the 'call service' node onto your flow.
- Click that node to view the configuration screen
- click the 'Domains' field
- look through the available suggestions and see the lack of 'hassio'

## Proposed changes

Make the 'hassio' domain available if possible, or help me debug why this domain is missing from my add-on installation.

**Comment by tjorim** [comment] 2018-12-25 16:41
Hi, thanks for taking the time to report this issue.
However, I'm not entirely sure if it's caused by the add-on or the home-assistant-websocket node that is included.
It might be worth it to report the issue here as well: https://github.com/zachowj/node-red-contrib-home-assistant-websocket

**Comment by mrosseel** [comment] 2018-12-25 18:20
file a PR on the repo you provided: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/60

**Comment by frenck** [comment] 2019-01-01 09:49
Closing the issue on this end.

**Closed by frenck** 2019-01-01 09:49 UTC
