### ISSUE TITLE
Current version: 14.5.0 throws up "Deprecated API warning"

### ISSUE THREAD

**Issue by GwelforBodad** [hassio-addons/addon-node-red#1685] opened 2023-09-17 14:44 UTC
# Problem/Motivation
Updating Node-RED to the latest version results in a "Deprecated API warning" being generated in the debug window.  This appears to happen each time a state trigger value changes.

Deprecated API warning being generated about every second or so.  Stating:
```
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."
```
Every time the warning is generated, there's also an error:
```
"Error: ↵    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)↵    at JSONataService.evaluate (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)↵    at CallService.evaluateJSONata (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)↵    at CallService.onInput (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)↵    at CallService.preOnInput (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)↵    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26↵    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)↵    at callServiceNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)↵    at callServiceNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Nod..."
```
## Expected behavior
No warnings to be generated 

## Actual behavior
Warning being generated

## Steps to reproduce
```
Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest
Node-RED 14.5.0
```
Update home assistant and Node-RED to latest version, create a flow with state triggers and see the API warning
## Proposed changes
Presumably the Add-on needs to be updated to include the callback required.

**Comment by sinclairpaul** [comment] 2023-09-17 14:57
Duplicate of #1683

**Closed by sinclairpaul** 2023-09-17 14:57 UTC
