### ISSUE TITLE
Node-red not starting in docker version after upgrading Node-red

### ISSUE THREAD

**Issue by riddertommie** [hassio-addons/addon-node-red#74] opened 2018-11-09 12:39 UTC
# Problem/Motivation

Node-red not starting anymore

## Expected behavior

A working new release

## Actual behavior

Node red is going in a bootloop > see log

## Steps to reproduce

Installed hassio on docker via > https://github.com/home-assistant/hassio-build/blob/master/install/hassio_install

tried both stable and beta

Host system is ubuntu 18.04
Install Node-red via Addon store

Config it en start up, 'play' with it for a short time.

!!!I have the same setup on a rpi (not with docker) and no problems with that!!!
First started a issue on https://github.com/home-assistant/hassio-build/issues/122 bit they referred

## Proposed changes

?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

log file under this line
_____________________________________

[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...

Hass.io Add-on: Node-RED v1.1.0

Flow-based programming for the Internet of Things

From: Community Hass.io Add-ons
By: Franck Nijhof frenck@addons.community
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing...

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-warning.sh: executing...
WARNING: No users configured and authentication has been disabled!
WARNING: This is not recommended!!!
[cont-init.d] 11-warning.sh: exited 0.
[cont-init.d] 20-config.sh: executing...
[cont-init.d] 20-config.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing...
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing...
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing...
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

hassio-addon-node-red@1.0.0 start /opt
node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Error loading settings file: /etc/node-red/config.js
TypeError: Cannot read property 'length' of undefined
at Object. (/etc/node-red/config.js:27:19)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (/opt/node_modules/node-red/red.js:115:20)
at Module._compile (module.js:635:30)

hassio-addon-node-red@1.0.0 start /opt
node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Error loading settings file: /etc/node-red/config.js
TypeError: Cannot read property 'length' of undefined
at Object. (/etc/node-red/config.js:27:19)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (/opt/node_modules/node-red/red.js:115:20)

<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio-build">home-assistant/hassio-build</a></strong></div><div>:tractor: Hass.io build tools. Contribute to home-assistant/hassio-build development by creating an account on GitHub.</div></blockquote>

**Comment by stephanruttloff** [comment] 2018-11-14 10:43
Same problem here. Works for a few minutes before going into bootloop.

**Comment by riddertommie** [comment] 2018-11-20 15:58
Nobody?

**Comment by frenck** [comment] 2018-11-20 16:02
Really, I have no idea... 'length' is not used by the add-on code see:

https://github.com/hassio-addons/addon-node-red/blob/master/node-red/rootfs/etc/node-red/config.js

Search for `length` ;)

**Comment by ludeeus** [comment] 2018-11-20 16:37
I guess that is not the issue since it results in a completely different error...

**Comment by stephanruttloff** [comment] 2018-11-20 17:11
This is really strange. Looking at config.js in this repo, I too can't see the failing check but when I connect into the container it is there:

![image](https://user-images.githubusercontent.com/78763/48789841-3b88e900-ecee-11e8-9d77-b5719355077f.png)

I never installed this plugin before so it can't be some sort of leftover from an earlier version. Reinstalling it results in the same error. The installed version seems to be different to the latest state of this repo...

**Comment by frenck** [comment] 2018-11-20 17:29
What addons versions are you guys on? As in, the screenshot shows older code

**Comment by stephanruttloff** [comment] 2018-11-20 17:45
I installed the latest version (1.1.0) from the addon store. I just did a fresh install and config.js looks good after that:

![image](https://user-images.githubusercontent.com/78763/48792185-e18b2200-ecf3-11e8-8c91-1707865f1af4.png)

Somehow, the container gets recreated after some minutes with what seems to be an older version (containing the old config.js) 😮

**Comment by stephanruttloff** [comment] 2018-11-20 18:59
I think my issues were caused by Watchtower (I totally forgot that I set it up ages ago).
Disabling it solves my problem. Sorry for the trouble guys 😅

**Comment by riddertommie** [comment] 2018-11-21 08:54
Oeps...... I have that also. Will test and let you know.....

**Comment by riddertommie** [comment] 2018-11-21 17:51
Worked for me also, thanks @stephanruttloff  for leading the way.

i tried to start watchtower with --label-enable and exclude node-red with com.centurylinklabs.watchtower.enable = false 

but as soon as you add a label to the node-red container its start in boot loop again.

**Comment by frenck** [comment] 2018-11-21 18:08
Watchtower should not be used on Hass.io containers...

Since this actual issue is solved now, I'll go ahead and close this issue.

**Closed by frenck** 2018-11-21 18:08 UTC
