### ISSUE TITLE
Failed patching file nodes/ui_base.html after update to latest version

### ISSUE THREAD

**Issue by Dirktheman** [hassio-addons/addon-node-red#766] opened 2020-11-18 11:33 UTC
# Problem/Motivation
I updated to the latest version of addon-node-red, but it won't start anymore.

I tried uninstalling the addon and removed the entire nodered-folder on my Raspberry Pi, and re-installing it again from scratch. No luck.

The log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 7.2.9
 You are running the latest version of this add-on.
 System: HassOS 4.16  (armv7 / raspberrypi4)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 FAILED at 531.
1 out of 1 hunk FAILED -- saving rejects to file nodes/ui_base.html.rej
[cont-init.d] node-red.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by frenck** [comment] 2020-11-18 11:37
Duplicate of #764 and #765 

Please check existing issues before opening a new one. Gets you the answer faster, saves me the effort of handling duplicates.

Thanks 👍

**Closed by frenck** 2020-11-18 11:37 UTC
