### ISSUE TITLE
Han desaparecido mis flows.

### ISSUE THREAD

**Issue by Jadelcas** [hassio-addons/addon-node-red#1748] opened 2023-11-21 11:43 UTC
All my scripts were disappeared!!! Help

Edited: sorry, not my scritpts, I wanted to say: my flows

_Originally posted by @rubendediegomartinez in https://github.com/hassio-addons/addon-node-red/issues/1738#issuecomment-1812517583_

**Comment by Jadelcas** [comment] 2023-11-21 11:44
Me ha ocurrido lo mismo con la última actualización.

**Comment by tjorim** [comment] 2023-12-15 15:59
Duplicate of #1736.

**Closed by tjorim** 2023-12-15 15:59 UTC
