### ISSUE TITLE
google-tts-api is too old

### ISSUE THREAD

**Issue by Rad3d21** [hassio-addons/addon-node-red#846] opened 2021-01-17 15:55 UTC
# Problem/Motivation
Cannot use google-home-notify. key failed message

## Expected behavior
It should cause speech to come out of my home mini

## Actual behavior
error saying get key failed from google

## Steps to reproduce
just put timestamp as input to node-red-contrib-google-home-notify and the error will show

## Proposed changes

Upgrade google-tts-api from 0.0.5 to 2.0.1. This is the latest version and will probably work.

**Comment by frenck** [comment] 2021-01-17 15:57
Duplicate of #829
That is an issue with the `node-red-contrib-google-home-notify` node, please report the issue upstream.

**Closed by frenck** 2021-01-17 15:57 UTC
