### ISSUE TITLE
Image does not exist prevents start

### ISSUE THREAD

**Issue by thedavidhanks** [hassio-addons/addon-node-red#1374] opened 2022-06-09 13:12 UTC
After the update to 12.0.2 I'm receiving the following error when starting node red:

> 2022-06-09 08:34:41 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a0d7b954_nodered/start - Image ghcr.io/hassio-addons/node-red/amd64:12.0.2 does not exist for addon_a0d7b954_nodered

As a result node red fails to start.

System info:

Home Assistant OS | 8.1
Home Assistant Supervisor | 2022.05.3
HS Core | 2022.6.4
Development | false
Docker | true
Operating System Family | Linux
Operating System Version | 5.15.41
CPU Architecture | x86_64

**Comment by frenck** [comment] 2022-06-09 13:13
Duplicate of #1373

@thedavidhanks Could you check the mentioned solution in #1373 to see if that solves it for you?

**Closed by frenck** 2022-06-09 13:13 UTC
