### ISSUE TITLE
Recurring error in debug after update

### ISSUE THREAD

**Issue by obaldius** [hassio-addons/addon-node-red#1696] opened 2023-10-04 09:33 UTC
Just updated and I'm finding this error in debug trigger more than 60 times a minutes, how can I stop it?

![image](https://github.com/hassio-addons/addon-node-red/assets/61756214/71eac7d9-9f94-440a-bb09-8d1cf7f268df)

**Comment by tonydm** [comment] 2023-10-04 15:55
Same here.  I too just updated, showing v14.5.0 (Latest update prompt as of 10/2/23).  Blowing up my debug window.

OS: HA OS 10.5
Core: 2023.9.3

Thank you for your time and effort

**Comment by henriklund** [comment] 2023-10-06 18:55
Please look [here](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/898). After update to latest version (v14.6.0 released today) + update of the Node-RED Companion to v3.0.1, the issue is gone in my installation.

**Comment by frenck** [comment] 2023-10-06 18:59
Closing as it has been solved in the latest version.

../Frenck

**Closed by frenck** 2023-10-06 18:59 UTC
