### ISSUE TITLE
No info below Nodes and non functional injection nodes after upgrade to 18.1.1.

### ISSUE THREAD

**Issue by kersten-lohmeyer** [hassio-addons/addon-node-red#1958] opened 2024-10-01 15:09 UTC
# Problem/Motivation

No info below nodes and non functional injection nodes after upgrade to 18.1.1. Most current HA version.

## Expected behavior

Info below nodes like "running...", state, etc. Injection nodes should be clickable and not greyed out.

## Actual behavior

No info below nodes and non functional injection nodes. No cache issue, tried with Chrome and Firefox.

## Steps to reproduce

upgrade to 18.1.1.

But Node Red seems to work and does trigger things. It just doesn't show the info and time below the nodes. Also injection nodes don't work as I wrote. No errors in the log btw. Restarting the host doesn't fix it.

Also: https://community.home-assistant.io/t/node-red-18-1-1/777163

<img width="964" alt="image" src="https://github.com/user-attachments/assets/13792c8d-fd6a-41a0-a3f4-972eea6e265e">

**Comment by tjorim** [comment] 2024-10-01 17:00
Duplicate of #1938.

**Closed by tjorim** 2024-10-01 17:00 UTC
