### ISSUE TITLE
Hassio "This add-on is not available on your system."

### ISSUE THREAD

**Issue by nara** [hassio-addons/addon-node-red#210] opened 2019-04-25 04:28 UTC
# Problem/Motivation
Hassio newbie here. I installed hassio on raspberry pi 3b using 32bit version hassio. From add-on store, I see "This add-on is not available on your system." message and install is disabled. 
here is uname -a shows on my pi

Linux core-ssh 4.14.98-v7 #1 SMP Thu Mar 21 17:56:48 UTC 2019 armv7l Linux

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment] 2019-04-25 07:12
Duplicate of #208.

**Comment by iVexilar** [comment] 2019-04-25 11:30
Update your Hass.Io, You need version 92.0 to install the update.

**Closed** 2019-04-25 12:24 UTC
