### ISSUE TITLE
Enabling support for node-red projects

### ISSUE THREAD

**Issue by garethhowell** [hassio-addons/addon-node-red#1590] opened 2023-04-07 10:36 UTC
I want to make use of the project feature in my node-red add-on. To work properly, I need to add my ssh id_rsa.pub file so the repo can be updated.

According to the node-red docs, it expects to find the id files in ~/.ssh. Unfortunately, being a docker container, I don’t have access to that folder.

Has anybody cracked this?

**Comment by frenck** [comment] 2023-04-10 14:26
Closing this, as this is not a bug report.

**Closed by frenck** 2023-04-10 14:26 UTC
